/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NX50bJKCLKo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function join() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div
        className="container grid max-w-3xl items-center justify-center gap-8 px-4 md:px-6">
        <div className="space-y-4 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Join the Cognitive Cleanse Community
          </h2>
          <p
            className="text-gray-500 dark:text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Connect with like-minded individuals, share insights, and embark on a journey of mental well-being.
          </p>
        </div>
        <Card className="w-full">
          <CardContent>
            <form className="grid gap-4">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="Enter your email" type="email" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="message">Message or Feedback</Label>
                <Textarea
                  className="min-h-[100px]"
                  id="message"
                  placeholder="Share your thoughts or feedback" />
              </div>
              <div className="items-top flex space-x-2">
                <Checkbox id="newsletter" />
                <div className="grid gap-1.5 leading-none">
                  <Label
                    className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                    htmlFor="newsletter">
                    Subscribe to the newsletter
                  </Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Stay up-to-date with the latest community updates and resources.
                  </p>
                </div>
              </div>
              <Button className="w-full" type="submit">
                Join the Community
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </section>)
  );
}
