/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/38TuKHjysLG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export default function support() {
  return (
    (<section className="w-full py-12 md:py-24 h-screen lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div
          className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12 xl:grid-cols-[1fr_550px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <div
                className=" text-white inline-block rounded-lg bg-gray-100 px-30 py-1 text-sm dark:bg-gray-800">
                Personal Support
              </div>
              <h2 className="text-[#805ad5] text-3xl font-bold tracking-tighter sm:text-5xl">Connect with our Experts</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Get personalized guidance and support for your cognitive cleansing journey. Our team of experts is here
                to help you every step of the way.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Button className="w-full min-[400px]:w-auto " variant="secondary">
                Chat with an Expert
              </Button>
              <Button className="w-full min-[400px]:w-auto" variant="secondary">
                Schedule a Call
              </Button>
            </div>
          </div>
          <img
            alt="Personal Support"
            className="mx-auto  overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            height="1920"
            src="/Therapy.svg"
            width="1080" />
        </div>
      </div>
     
    </section>
    )
    
  );
}
